vscode:
  extensions:
  - golang.Go
tasks:
  - init: go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
    command: source <(setup-envtest use -p env 1.23.x)
  - command: curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH) && chmod +x kubebuilder && sudo mv kubebuilder /usr/local/bin/
  - command: go install honnef.co/go/tools/cmd/staticcheck@latest
  - init: |
      mkdir bin \
      && ln -s /workspace/go/bin/controller-gen bin/ \ 
      && ln -s /workspace/go/bin/setup-envtest bin/