vscode:
  extensions:
  - golang.Go
tasks:
  - command: curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH) && chmod +x kubebuilder && sudo mv kubebuilder /usr/local/bin/
  - command: go install honnef.co/go/tools/cmd/staticcheck@latest
  - command: ln -s /workspace/go/bin bin
