# permissions for end users to edit imageflowtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imageflowtemplate-editor-role
rules:
- apiGroups:
  - build.takutakahashi.dev
  resources:
  - imageflowtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - build.takutakahashi.dev
  resources:
  - imageflowtemplates/status
  verbs:
  - get
