apiVersion: build.takutakahashi.dev/v1beta1
kind: ImageFlowTemplate
metadata:
  name: imageflowtemplate-sample
spec:
  detect:
    requiredEnv:
    - GITHUB_TOKEN
    actor:
      name: main
      image: "ghcr.io/takutakahashi/oci-image-operator/actor-github:beta"
      env:
        - name: GITHUB_TOKEN
          envFrom:
            secretKeyRef:
              name: ghcr-pat
              key: GITHUB_TOKEN
  check:
    actor:
      name: main
      image: "ghcr.io/takutakahashi/oci-image-operator/actor-noop:beta"
  upload:
    actor:
      name: main
      image: "ghcr.io/takutakahashi/oci-image-operator/actor-noop:beta"