apiVersion: build.takutakahashi.dev/v1beta1
kind: ImageFlowTemplate
metadata:
  name: imageflowtemplate-sample
spec:
  detect:
    requiredEnv:
    - GITHUB_TOKEN
    actor:
      name: main
      image: "ghcr.io/takutakahashi/oci-image-operator/actor-github:v0.1.12"
      env:
        - name: GITHUB_ORG
          value: takutakahashi
        - name: GITHUB_REPO
          value: build-test
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: ghcr-pat
              key: GITHUB_TOKEN
  check:
    actor:
      name: main
      image: "ghcr.io/takutakahashi/oci-image-operator/actor-registryv2:beta"
  upload:
    actor:
      name: main
      image: "ghcr.io/takutakahashi/oci-image-operator/actor-noop:beta"
