apiVersion: build.takutakahashi.dev/v1beta1
kind: Image
metadata:
  name: image-sample
spec:
  templateName: imageflowtemplate-sample
  repository:
    url: https://github.com/takutakahashi/testbed.git
    tagPolicies:
    - policy: branchHash
      revision: master
  targets:
  - name: ghcr.io/takutakahashi/testbed