apiVersion: build.takutakahashi.dev/v1beta1
kind: ImageFlowTemplate
metadata:
  name: imageflowtemplate-sample
spec:
  detect:
    actor:
      name: main
      image: "ghcr.io/takutakahashi/oci-image-operator/actor-noop:beta"
  check:
    actor:
      name: main
      image: "ghcr.io/takutakahashi/oci-image-operator/actor-noop:beta"
  upload:
    actor:
      name: main
      image: "ghcr.io/takutakahashi/oci-image-operator/actor-noop:beta"