apiVersion: build.takutakahashi.dev/v1beta1
kind: Image
metadata:
  name: image-sample
spec:
  templateName: imageflowtemplate-sample
  repository:
    url: https://github.com/takutakahashi/build-test.git
    tagPolicies:
    - policy: branchHash
      revision: main
  targets:
  - name: ghcr.io/takutakahashi/build-test
    auth:
      type: basic
      secretName: ghcr-pat
