---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: oci-image-operator:actor-detect
rules:
- apiGroups:
  - build.takutakahashi.dev
  resources:
  - imageflowtemplates
  verbs:
  - get
  - list
- apiGroups:
  - build.takutakahashi.dev
  resources:
  - images
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - build.takutakahashi.dev
  resources:
  - images/finalizers
  verbs:
  - update
- apiGroups:
  - build.takutakahashi.dev
  resources:
  - images/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oci-image-operator:actor-detect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: actor-detect
  namespace: system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actor-detect
  namespace: system