on:
  push:
    branches:

name: CI

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: takutakahashi/oci-image-operator
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.1
      - run: |
          make test
      - run: |
          make -C actor/base test
